/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package club_de_langue;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author BEST
 */
public final class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     * @throws java.sql.SQLException
     */
    public NewJFrame() throws SQLException {
        initComponents();
        init();
        callPanelClubs();
        jTabPaneClub.setSelectedIndex(0);
    }
    
    public void callPanelClubs(){
        Connection connect = null;
            try {
                ConnectionDb.Charge();
		connect = ConnectionDb.getConnection();
		Statement cursor = connect.createStatement();
                String sql = "select * from club_langage.leaderClub";
		ResultSet result = cursor.executeQuery(sql);
		while(result.next()) {
                    String clubName = result.getString("club");
                    NewClub myClub = new NewClub(clubName,jTabPaneClub);
		}
                jTabPaneClub.insertTab("+", null, jPanelCreateClub, null, jTabPaneClub.getTabCount());
                jTabPaneClub.setSelectedIndex(jTabPaneClub.getTabCount() - 1);
            }catch(ClassNotFoundException e) {
		System.out.println("echec du chargement du driver");
            } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }finally {
                // Fermer la connexion
                if (connect != null) {
                    try {
                        connect.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }
    
    public void init() throws SQLException{
        verifyDateIsPassed();
        setTime();
        LocalDate currentDate = LocalDate.now();
        LocalTime currentTime = LocalTime.now();
        String cDate = String.valueOf(currentDate);
        String cTime = String.valueOf(currentTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabPaneClub = new javax.swing.JTabbedPane();
        jPanelCreateClub = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jTextFieldName_NC = new javax.swing.JTextField();
        jLabel108 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jTextFieldNameLeader_NC = new javax.swing.JTextField();
        jTextFieldLastnameLeader_NC = new javax.swing.JTextField();
        jTextFieldBirthdayLeader_NC = new javax.swing.JTextField();
        jTextFieldAdressLeader_NC = new javax.swing.JTextField();
        jTextFieldEmailLeader_NC = new javax.swing.JTextField();
        jTextFieldTelLeader_NC = new javax.swing.JTextField();
        jButtonCreateClub = new javax.swing.JButton();
        jTextFieldMessage_NC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNameClubDeleted = new javax.swing.JTextField();
        jButtonDeleteClub = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jTxDate = new javax.swing.JLabel();
        jTxTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des clubs de langue");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(37, 91, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icone.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mes Clubs");

        jTabPaneClub.setBackground(new java.awt.Color(45, 104, 50));
        jTabPaneClub.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel30.setBackground(new java.awt.Color(45, 104, 50));
        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Créer votre club", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 21), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel30MouseExited(evt);
            }
        });
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel31.setBackground(new java.awt.Color(45, 130, 50));
        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Le club", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel108.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(255, 255, 255));
        jLabel108.setText("Nom");

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel108)
                    .addComponent(jTextFieldName_NC, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel108)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldName_NC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 140));

        jPanel32.setBackground(new java.awt.Color(45, 130, 50));
        jPanel32.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Qui est le dirigeant ?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel110.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(255, 255, 255));
        jLabel110.setText("Nom");

        jLabel111.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(255, 255, 255));
        jLabel111.setText("Prénoms");

        jLabel112.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(255, 255, 255));
        jLabel112.setText("Date de naissance");

        jLabel113.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(255, 255, 255));
        jLabel113.setText("Adresse");

        jLabel114.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(255, 255, 255));
        jLabel114.setText("Email");

        jLabel115.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(255, 255, 255));
        jLabel115.setText("Téléphone");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNameLeader_NC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel110))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLastnameLeader_NC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel111))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBirthdayLeader_NC, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel112))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAdressLeader_NC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel113))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmailLeader_NC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel114))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel115)
                    .addComponent(jTextFieldTelLeader_NC, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel110)
                    .addComponent(jLabel111)
                    .addComponent(jLabel112)
                    .addComponent(jLabel114)
                    .addComponent(jLabel115)
                    .addComponent(jLabel113))
                .addGap(18, 18, 18)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNameLeader_NC)
                    .addComponent(jTextFieldBirthdayLeader_NC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLastnameLeader_NC)
                    .addComponent(jTextFieldAdressLeader_NC)
                    .addComponent(jTextFieldEmailLeader_NC)
                    .addComponent(jTextFieldTelLeader_NC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel30.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 930, 140));

        jButtonCreateClub.setBackground(new java.awt.Color(0, 204, 204));
        jButtonCreateClub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plusClub.png"))); // NOI18N
        jButtonCreateClub.setText("  Créer");
        jButtonCreateClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateClubMouseClicked(evt);
            }
        });
        jButtonCreateClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateClubActionPerformed(evt);
            }
        });
        jPanel30.add(jButtonCreateClub, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 230, 100, 40));

        jTextFieldMessage_NC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldMessage_NC.setForeground(new java.awt.Color(255, 51, 51));
        jPanel30.add(jTextFieldMessage_NC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 500, 30));

        jPanel2.setBackground(new java.awt.Color(45, 104, 50));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supprimer une club", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 21), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom du club : ");

        jButtonDeleteClub.setBackground(new java.awt.Color(255, 0, 0));
        jButtonDeleteClub.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDeleteClub.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteClub.setText("Suppression total!!!");
        jButtonDeleteClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDeleteClubMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Attention!!!");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Si vous cliquez sur \"Suppression total!!!\", vous supprimer litéralement le club et avec elle, tous ses données(dirigeant,");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("les activités et même les membres).");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Donc, saisisez le nom du club si vous êtez sûr et certain.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(60, 60, 60)
                        .addComponent(jTextFieldNameClubDeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonDeleteClub, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNameClubDeleted, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonDeleteClub, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attention.png"))); // NOI18N

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondClubs.png"))); // NOI18N

        javax.swing.GroupLayout jPanelCreateClubLayout = new javax.swing.GroupLayout(jPanelCreateClub);
        jPanelCreateClub.setLayout(jPanelCreateClubLayout);
        jPanelCreateClubLayout.setHorizontalGroup(
            jPanelCreateClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateClubLayout.createSequentialGroup()
                .addGroup(jPanelCreateClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelCreateClubLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCreateClubLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanelCreateClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCreateClubLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel67)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelCreateClubLayout.setVerticalGroup(
            jPanelCreateClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateClubLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCreateClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(jPanelCreateClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCreateClubLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel67)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabPaneClub.addTab("", new javax.swing.ImageIcon(getClass().getResource("/images/plusClub.png")), jPanelCreateClub); // NOI18N

        jTxDate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTxDate.setForeground(new java.awt.Color(255, 255, 255));
        jTxDate.setText("date");

        jTxTime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTxTime.setForeground(new java.awt.Color(255, 255, 255));
        jTxTime.setText("time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabPaneClub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabPaneClub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("iconeMenu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonCreateClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateClubMouseClicked
        if("".equals(jTextFieldName_NC.getText()) || "".equals(jTextFieldNameLeader_NC.getText()) || 
                "".equals(jTextFieldLastnameLeader_NC.getText()) || "".equals(jTextFieldBirthdayLeader_NC.getText()) ||
                "".equals(jTextFieldEmailLeader_NC.getText()) || "".equals(jTextFieldAdressLeader_NC.getText()) ||
                "".equals(jTextFieldTelLeader_NC.getText())){
            jTextFieldMessage_NC.setForeground(new java.awt.Color(255, 51, 51));
            jTextFieldMessage_NC.setText("Remplire les informations sur votre club.");
        }else{
            Connection connect = null;
            String nameNewClub = String.valueOf(jTextFieldName_NC.getText());
            String nameLead = String.valueOf(jTextFieldNameLeader_NC.getText());
            String lastnameLead = String.valueOf(jTextFieldLastnameLeader_NC.getText());
            String birthdayLead = String.valueOf(jTextFieldBirthdayLeader_NC.getText());
            String emailLead = String.valueOf(jTextFieldEmailLeader_NC.getText());
            String adressLead = String.valueOf(jTextFieldAdressLeader_NC.getText());
            String telLead = String.valueOf(jTextFieldTelLeader_NC.getText());
            try {
                ConnectionDb.Charge();
                connect = ConnectionDb.getConnection();
                Statement st = connect.createStatement();
                String queryAddMember = "INSERT INTO club_langage.leaderClub(nom,prenoms,date_de_naissance,"
                        + "adresse,email,telephone,club) VALUE('"+nameLead+"',"
                        + "'"+lastnameLead+"','"+birthdayLead+"','"+adressLead+"',"
                        + "'"+emailLead+"','"+telLead+"','"+nameNewClub+"')";
                
                st.executeUpdate(queryAddMember);
                NewClub myNewClub = new NewClub(nameNewClub,jTabPaneClub);
                jTextFieldName_NC.setText("");
                jTextFieldNameLeader_NC.setText("");
                jTextFieldLastnameLeader_NC.setText("");
                jTextFieldBirthdayLeader_NC.setText("");
                jTextFieldEmailLeader_NC.setText("");
                jTextFieldAdressLeader_NC.setText("");
                jTextFieldTelLeader_NC.setText("");
                jTextFieldMessage_NC.setForeground(new java.awt.Color(51, 255, 51));
                jTextFieldMessage_NC.setText("Votre club est créé avec succés.");
                jTabPaneClub.insertTab("+", null, jPanelCreateClub, null, jTabPaneClub.getTabCount());
                jTabPaneClub.setSelectedIndex(jTabPaneClub.getTabCount() - 1);
                connect.close();
            } catch (ClassNotFoundException e) {
                System.out.println("echec du chargement du driver");
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                jTextFieldMessage_NC.setText("Insérer une date valide (exemple : 2000-12-31).");
            }
        }
        
    }//GEN-LAST:event_jButtonCreateClubMouseClicked

    private void jPanel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel30MouseEntered

    }//GEN-LAST:event_jPanel30MouseEntered

    private void jPanel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel30MouseExited
       
    }//GEN-LAST:event_jPanel30MouseExited

    private void jButtonCreateClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateClubActionPerformed

    private void jButtonDeleteClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteClubMouseClicked
        Connection connect = null;
        String deleteClub = String.valueOf(jTextFieldNameClubDeleted.getText());
        try {
            ConnectionDb.Charge();
            connect = ConnectionDb.getConnection();
            Statement st = connect.createStatement();
            String queryDeleteLeader = "DELETE FROM club_langage.leaderClub WHERE club='"+deleteClub+"'";
            String queryDeleteActivity = "DELETE FROM club_langage.activity WHERE club='"+deleteClub+"'";
            String queryDeleteMember = "DELETE FROM club_langage.member WHERE club='"+deleteClub+"'";
            st.executeUpdate(queryDeleteMember);
            st.executeUpdate(queryDeleteActivity);
            st.executeUpdate(queryDeleteLeader);
	    connect.close();
            NewJFrame.super.setVisible(false);
            new NewJFrame().setVisible(true);
        } catch (ClassNotFoundException e) {
            System.out.println("echec du chargement du driver");
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDeleteClubMouseClicked
    
    public void setTime(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                while(true){
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        
                    }
                    Date date = new Date();
                    SimpleDateFormat tf = new SimpleDateFormat("h:mm:ss aa");
                    SimpleDateFormat df = new SimpleDateFormat("EEEE, dd-MM-yyyy");
                    String time = tf.format(date);
                    jTxTime.setText(time.split(" ")[0]+" "+time.split(" ")[1]);
                    jTxDate.setText(df.format(date));
                }
            }
        }).start();
    }
    
    public void verifyDateIsPassed() throws SQLException{
        Connection connect = null;
        try {
            ConnectionDb.Charge();
            connect = ConnectionDb.getConnection();
            PreparedStatement selectStmt = connect.prepareStatement("SELECT * FROM club_langage.activity");
            ResultSet resultSet = selectStmt.executeQuery();
            PreparedStatement updateStmt = connect.prepareStatement("UPDATE club_langage.activity SET "
                     + "status = 'passé' WHERE id = ?");
                while (resultSet.next()) {
                    String date = String.valueOf(resultSet.getDate("date"));
                    String time = String.valueOf(resultSet.getTime("horaire"));
                    LocalDate currentDate = LocalDate.now();
                    LocalDate dateL = LocalDate.parse(date);
                    
                    LocalTime timeL = LocalTime.parse(time);
                    LocalTime currentTime = LocalTime.now();
                    Duration difference = Duration.between(timeL, currentTime);
                    long heures = difference.toHours(); // Récupération du nombre d'heures
                    long minutes = difference.toMinutes() % 60; // Récupération du nombre de minutes


                    if (dateL.isBefore(currentDate)) {
                        int id = resultSet.getInt("id");
                        updateStmt.setInt(1, id);
                        updateStmt.executeUpdate();
                    }else{
                        int id = resultSet.getInt("id");
                        long difDate = ChronoUnit.DAYS.between(currentDate, dateL);
                        PreparedStatement updateStatus = connect.prepareStatement("UPDATE "
                                + "club_langage.activity SET status = '"+difDate+"j "+heures+"h:"+minutes+"' "
                                        + "WHERE id = "+id+"");
                        updateStatus.executeUpdate();
                    }
            }
	    connect.close();
    }   catch (ClassNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateClub;
    private javax.swing.JButton jButtonDeleteClub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanelCreateClub;
    private javax.swing.JTabbedPane jTabPaneClub;
    private javax.swing.JTextField jTextFieldAdressLeader_NC;
    private javax.swing.JTextField jTextFieldBirthdayLeader_NC;
    private javax.swing.JTextField jTextFieldEmailLeader_NC;
    private javax.swing.JTextField jTextFieldLastnameLeader_NC;
    private javax.swing.JLabel jTextFieldMessage_NC;
    private javax.swing.JTextField jTextFieldNameClubDeleted;
    private javax.swing.JTextField jTextFieldNameLeader_NC;
    private javax.swing.JTextField jTextFieldName_NC;
    private javax.swing.JTextField jTextFieldTelLeader_NC;
    private javax.swing.JLabel jTxDate;
    private javax.swing.JLabel jTxTime;
    // End of variables declaration//GEN-END:variables
}
